[package]
name = "flock_gui_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7" }
flock_state_plugin = { path = "../flock_state_plugin" }
