on: [push]

name: Flock Playground

jobs:
  build_and_test:
    name: Build, test, fmt and clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install Bevy dependencies
        run: sudo apt update && sudo apt-get install g++ clang pkg-config libx11-dev libasound2-dev libudev-dev

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: run

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
